const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.DEMO_TEST_URL||'http://127.0.0.1:3000/';
const overflow=async page=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal page overflow');
const openNav=async page=>{if(await page.evaluate(()=>innerWidth<=760)&&!await page.locator('.original-sidebar').evaluate(el=>el.classList.contains('mobile-open')))await page.getByRole('button',{name:'Open navigation'}).click()};
const nav=async(page,name)=>{await openNav(page);await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:new RegExp('^'+name)}).click()};
const role=(page,name)=>page.getByRole('combobox',{name:'Demo role'}).selectOption(name);
const space=async(page,id)=>{await openNav(page);await page.getByRole('combobox',{name:'Active space'}).selectOption(id)};
const submit=async page=>{await page.getByRole('button',{name:'Review request',exact:true}).click();await page.getByRole('button',{name:'Submit request',exact:true}).click();await page.getByRole('heading',{name:'Ready for review'}).waitFor()};
const approveRun=async page=>{await page.getByRole('button',{name:'Approve demo request'}).click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor()};
const manage=(page,name)=>page.getByRole('button',{name:`Manage ${name}`,exact:true}).click();
const noTechnical=async page=>{assert.equal(await page.locator('.service-detail,.request-detail,.automation,.request-form,.reporting-settings,.original-global-search').count(),0);for(const label of ['Request a service','Connected tools','Database inventory','Lifecycle operations','Golden paths','Backup & recovery','Agentless sync'])assert.equal(await page.getByRole('button',{name:label,exact:true}).count(),0);const body=await page.locator('.original-main-area').textContent();for(const value of ['policy-servicing-prod','finance-core-db','claims-documents-dev','.demo.internal','CHG-','DB-102','AAP #','2026.10-001'])assert(!body.includes(value),`Management sees ${value}`)};
(async()=>{const browser=await chromium.launch({executablePath:fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined,headless:true,args:['--no-sandbox']});try{const errors=[],page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.getByRole('heading',{name:'A home for all your data.'}).waitFor();assert.equal(await page.locator('.original-platform-card').count(),6);assert.equal(await page.getByRole('combobox',{name:'Active space'}).locator('option').count(),1);assert(!await page.locator('main').textContent().then(t=>t.includes('finance-core-db')));await nav(page,'My databases');assert.equal(await page.locator('.original-inventory tbody tr').count(),1);
// Personal provisioning is owned by the developer; another platform space cannot review it.
await nav(page,'Service catalog');await page.getByRole('button',{name:'Request MongoDB',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Platform',exact:true}).inputValue(),'mongodb');await page.getByRole('radio',{name:/Large/}).check();await page.getByRole('textbox',{name:'Service name'}).fill('personal-mongo');await submit(page);assert.equal(await page.getByRole('button',{name:'Approve demo request'}).count(),0);await role(page,'DBRE');assert.equal(await page.getByRole('combobox',{name:'Active space'}).inputValue(),'platform-postgres');await nav(page,'Requests');assert.equal(await page.locator('.request-row').filter({hasText:'personal-mongo'}).count(),0);await space(page,'platform-mongodb');await nav(page,'Requests');await page.locator('.request-row').filter({hasText:'personal-mongo'}).click();await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByText('Large · 128 GB',{exact:true}).waitFor();await role(page,'Developer');await nav(page,'My databases');assert.equal(await page.locator('.original-inventory tbody tr').count(),2);
// A space change clears prior dialogs/details and scopes catalog, inventory and approvals.
await role(page,'DBRE');await space(page,'platform-oracle');assert.equal(await page.locator('.original-platform-card').count(),1);await nav(page,'Database inventory');assert.equal(await page.locator('.original-inventory tbody tr').count(),1);await manage(page,'finance-core-db');await page.getByRole('button',{name:'Review fix',exact:true}).click();await space(page,'platform-postgres');assert.equal(await page.getByRole('dialog').count(),0);assert(!await page.locator('main').textContent().then(t=>t.includes('finance-core-db')));await space(page,'platform-oracle');await nav(page,'Database inventory');await manage(page,'finance-core-db');await page.getByRole('button',{name:'Review fix',exact:true}).click();await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Run now');await submit(page);const baselineId=await page.locator('.request-detail>.page-title p').textContent();await nav(page,'Golden paths');await page.getByRole('button',{name:'Configure',exact:true}).first().click();await page.getByRole('textbox',{name:'AAP template ID'}).fill('96');await page.getByRole('textbox',{name:'Pinned Git SHA'}).fill('abc1234');await page.getByRole('button',{name:'Publish demo revision'}).click();await page.getByText('v1.3',{exact:true}).waitFor();await nav(page,'Requests');await page.locator('.request-row').filter({hasText:'Apply baseline'}).first().click();await page.getByText('Execution details',{exact:true}).click();await page.getByText('AAP #42 · a7c24f1',{exact:true}).waitFor();await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByText('Aligned',{exact:true}).waitFor();
await page.getByRole('button',{name:'Request an action'}).click();await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('Patch');await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Next maintenance window');await submit(page);await page.getByRole('button',{name:'Approve demo request'}).click();await page.getByRole('button',{name:'Schedule demo',exact:true}).click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor();
// DBRE provisioning is limited to the active platform.
await nav(page,'Service catalog');await page.getByRole('button',{name:'Request Oracle',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Platform',exact:true}).locator('option').count(),1);await page.keyboard.press('Escape');
// Restore and schema state remain scoped and personal ownership follows clones.
await space(page,'platform-postgres');await nav(page,'Database inventory');await manage(page,'policy-servicing-prod');await page.getByRole('tab',{name:'Recovery',exact:true}).click();await page.getByRole('button',{name:/^Restore clone/}).first().click();await page.getByRole('textbox',{name:'Development clone name'}).fill('personal-clone');await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('heading',{name:'personal-clone'}).waitFor();await nav(page,'Database inventory');await manage(page,'policy-servicing-prod');await page.getByRole('tab',{name:'Changes',exact:true}).click();await page.getByRole('button',{name:'Review changes'}).click();await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('tab',{name:'Changes',exact:true}).click();assert.equal(await page.locator('.changes-list').getByText('Applied',{exact:true}).count(),3);await page.getByRole('button',{name:'Request defined rollback'}).click();await submit(page);await approveRun(page);
// Freshness gates execution; a reporting space cannot ingest another platform's evidence.
await space(page,'platform-db2');await nav(page,'Database inventory');await manage(page,'underwriting-warehouse');await page.getByRole('button',{name:'Request an action'}).click();await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('Restart');await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Run now');await submit(page);await page.getByRole('button',{name:'Approve demo request'}).click();assert(await page.getByRole('button',{name:'Run demo',exact:true}).isDisabled());await nav(page,'Agentless sync');await page.getByRole('button',{name:'Open observation contract',exact:false}).click();await page.getByText('Test an observation',{exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Reporting service'}).locator('option').count(),1);await page.getByRole('button',{name:'Validate & ingest demo'}).click();await page.getByText('Accepted. Service state updated.',{exact:true}).waitFor();await page.getByRole('button',{name:'Duplicate',exact:true}).click();await page.getByRole('button',{name:'Validate & ingest demo'}).click();await page.getByRole('alert').getByText('Duplicate event.',{exact:false}).waitFor();const payload=JSON.parse(await page.getByRole('textbox',{name:'Observation JSON'}).inputValue());payload.serviceId='DB-1024';payload.eventId='foreign-service';await page.getByRole('textbox',{name:'Observation JSON'}).fill(JSON.stringify(payload));await page.getByRole('button',{name:'Validate & ingest demo'}).click();await page.getByRole('alert').getByText('Unknown serviceId.',{exact:false}).waitFor();await page.keyboard.press('Escape');await nav(page,'Requests');await page.locator('.request-row').filter({hasText:'Restart'}).first().click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor();
// Management has a sanitized fleet projection and no technical entry points.
await role(page,'Management');await page.getByRole('heading',{name:'Your fleet, at a glance.'}).waitFor();await noTechnical(page);assert.equal(await page.locator('.original-stat').first().locator('strong').textContent(),'8');await nav(page,'Fleet insights');await noTechnical(page);await space(page,'business-policy');assert.equal(await page.locator('.original-stat').first().locator('strong').textContent(),'3');await noTechnical(page);await nav(page,'Business portfolio');await noTechnical(page);
// Tours preserve the current context; management tours never expose technical screens.
await page.getByRole('button',{name:'Guided manager demo'}).click();await page.keyboard.press('Tab');assert(await page.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)));for(let i=0;i<5;i++){assert.equal(await page.locator('.service-detail,.request-detail,.automation').count(),0);await page.getByRole('button',{name:'Next',exact:true}).click()}await page.getByRole('button',{name:'Explore BasePort'}).click();assert.equal(await page.getByRole('combobox',{name:'Active space'}).inputValue(),'business-policy');await page.getByRole('heading',{name:'Business portfolio',exact:true,level:1}).waitFor();await noTechnical(page);
await role(page,'DBRE');await space(page,'platform-oracle');await page.getByRole('button',{name:'Guided manager demo'}).click();await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('combobox',{name:'Try a platform space'}).selectOption('postgres');await page.getByRole('button',{name:'Next',exact:true}).click();await page.locator('.service-detail h1').waitFor();assert(!await page.locator('.service-detail').textContent().then(t=>t.includes('finance-core-db')));assert.equal(await page.getByRole('combobox',{name:'Active space',includeHidden:true}).inputValue(),'platform-postgres');await page.keyboard.press('Escape');assert.equal(await page.getByRole('combobox',{name:'Active space'}).inputValue(),'platform-oracle');
// Responsive original sidebar and all space types at narrow sizes.
for(const width of [390,320]){await page.setViewportSize({width,height:844});for(const name of ['Developer','DBRE','Management']){await role(page,name);await overflow(page);await openNav(page);await overflow(page);await page.getByRole('button',{name:'Close navigation',exact:true}).first().click();if(name==='Management'){await noTechnical(page);await nav(page,'Fleet insights');await overflow(page)}else{await nav(page,name==='Developer'?'My databases':'Database inventory');await overflow(page);await manage(page,'policy-servicing-prod');await overflow(page);await page.getByRole('button',{name:'Request an action'}).click();await overflow(page);await page.keyboard.press('Escape')}}}
await page.goto(base+'?view=management&space=platform-oracle');await page.getByRole('heading',{name:'Your fleet, at a glance.'}).waitFor();assert.equal(await page.getByRole('combobox',{name:'Active space'}).inputValue(),'fleet');await noTechnical(page);
await page.goto(base+'?demo=binaya');await page.getByRole('dialog',{name:'BasePort · manager tour'}).waitFor();assert.equal(await page.getByRole('combobox',{name:'Demo role',includeHidden:true}).inputValue(),'Management');await page.keyboard.press('Escape');await noTechnical(page);assert.deepEqual(errors,[]);console.log('Original UI + spaces passed: sidebar/dashboard, personal ownership, platform-scoped records and actions, automation isolation, approvals, recovery, schema, agentless bounds, aggregate-only management, tours and 320/390px layouts.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
