const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.DEMO_TEST_URL||'http://127.0.0.1:3000/';
const overflow=async page=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal page overflow');
const nav=(page,name)=>page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:new RegExp('^'+name)});
const submit=async page=>{await page.getByRole('button',{name:'Review request',exact:true}).click();await page.getByRole('button',{name:'Submit request',exact:true}).click();await page.getByRole('heading',{name:'Ready for review'}).waitFor()};
const approveRun=async page=>{await page.getByRole('button',{name:'Approve demo request'}).click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor()};
(async()=>{
 const browser=await chromium.launch({executablePath:fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined,headless:true,args:['--no-sandbox']});
 const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('heading',{name:'My services',exact:true}).waitFor();assert.equal(await page.locator('.service-row').count(),1);assert.equal(await nav(page,'Automation').count(),0);
 // Developer creates a request; the DBRE explicitly reviews and completes it.
 await page.getByRole('button',{name:'New service',exact:true}).click();await page.getByRole('textbox',{name:'Service name'}).fill('policy-poc-dev');await submit(page);assert.equal(await page.getByRole('button',{name:'Approve demo request'}).count(),0);
 await page.getByRole('button',{name:'DBRE',exact:true}).click();await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('heading',{name:'policy-poc-dev'}).waitFor();await page.getByRole('button',{name:'Refresh state',exact:true}).first().click();await page.getByRole('status').getByText('Fresh observation accepted.',{exact:false}).waitFor();await page.getByText('Unprotected',{exact:true}).waitFor();
 await nav(page,'Services').click();assert.equal(await page.locator('.service-row').count(),7);
 // Repair drift through the same review flow; a scheduled request remains actionable.
 await page.locator('.service-row').filter({hasText:'finance-core-db'}).click();await page.getByRole('button',{name:'Review fix',exact:true}).click();await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Run now');await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByText('Aligned',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Request an action'}).click();await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('Patch');await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Next maintenance window');await submit(page);await page.getByRole('button',{name:'Approve demo request'}).click();await page.getByRole('button',{name:'Schedule demo',exact:true}).click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor();
 // Restore clone leaves its source intact and starts with unresolved protection.
 await nav(page,'Services').click();await page.locator('.service-row').filter({hasText:'policy-servicing-prod'}).click();await page.getByRole('tab',{name:'Recovery',exact:true}).click();await page.getByRole('button',{name:/^Restore clone/}).first().click();await page.getByRole('textbox',{name:'Development clone name'}).fill('policy-recovery-clone');await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('heading',{name:'policy-recovery-clone'}).waitFor();
 await nav(page,'Services').click();await page.locator('.service-row').filter({hasText:'policy-servicing-prod'}).click();await page.getByRole('tab',{name:'Changes',exact:true}).click();await page.getByRole('button',{name:'Review changes'}).click();await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('tab',{name:'Changes',exact:true}).click();assert.equal(await page.locator('.changes-list').getByText('Applied',{exact:true}).count(),3);
 await page.getByRole('button',{name:'Request defined rollback'}).click();await submit(page);await approveRun(page);await page.getByRole('button',{name:'Open service',exact:true}).click();await page.getByRole('tab',{name:'Changes',exact:true}).click();assert.equal(await page.locator('.changes-list').getByText('Pending',{exact:true}).count(),2);
 // Stale facts gate actions; agentless refresh and contract rejection work.
 await nav(page,'Services').click();await page.locator('.service-row').filter({hasText:'underwriting-warehouse'}).click();await page.getByRole('button',{name:'Request an action'}).click();await page.getByRole('combobox',{name:'Action',exact:true}).selectOption('Restart');await page.getByRole('combobox',{name:'Window',exact:true}).selectOption('Run now');await submit(page);await page.getByRole('button',{name:'Approve demo request'}).click();assert(await page.getByRole('button',{name:'Run demo',exact:true}).isDisabled());
 await nav(page,'Services').click();await page.locator('.service-row').filter({hasText:'underwriting-warehouse'}).click();await page.getByRole('button',{name:'Refresh state',exact:true}).first().click();await page.getByRole('status').getByText('Fresh observation accepted.',{exact:false}).waitFor();await nav(page,'Requests').click();await page.locator('.request-row').filter({hasText:'Restart'}).first().click();await page.getByRole('button',{name:'Run demo',exact:true}).click();await page.getByRole('heading',{name:'Completed',exact:true}).waitFor();
 await nav(page,'Automation').click();await page.getByRole('button',{name:'Configure',exact:true}).first().click();await page.getByRole('textbox',{name:'AAP template ID'}).fill('92');await page.getByRole('textbox',{name:'Pinned Git SHA'}).fill('abcd123');await page.getByRole('button',{name:'Publish demo revision'}).click();await page.getByText('v1.3',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Agentless reporting',exact:true}).click();await page.getByText('Test an observation',{exact:true}).click();await page.getByRole('button',{name:'Validate & ingest demo'}).click();await page.getByText('Accepted. Service state updated.',{exact:true}).waitFor();await page.getByRole('button',{name:'Duplicate',exact:true}).click();await page.getByRole('button',{name:'Validate & ingest demo'}).click();await page.getByRole('alert').getByText('Duplicate event.',{exact:false}).waitFor();await page.keyboard.press('Escape');
 // Tour is temporary; it restores the previous screen and user-created service records.
 await nav(page,'Services').click();const count=await page.locator('.service-row').count();await page.getByRole('button',{name:'Take the tour'}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Tab');assert(await page.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)));await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('combobox',{name:'Try a platform'}).selectOption('oracle');await page.getByRole('button',{name:'Next',exact:true}).click();await page.locator('h1').filter({hasText:'finance-core-db'}).waitFor();for(let i=0;i<3;i++)await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Explore BasePort'}).click();assert.equal(await page.locator('.service-row').count(),count);assert(await page.locator('.service-row').filter({hasText:'policy-poc-dev'}).count());
 await overflow(page);await page.screenshot({path:'.playwright/simple-desktop.png'});
 // All six platforms and responsive service/detail/request/automation/tour screens.
 for(const width of [390,320]){await page.setViewportSize({width,height:844});await nav(page,'Services').click();await overflow(page);await page.locator('.service-row').filter({hasText:'policy-servicing-prod'}).click();await overflow(page);await page.getByRole('tab',{name:'Recovery',exact:true}).click();await overflow(page);await page.getByRole('button',{name:'Request backup'}).click();await overflow(page);await page.keyboard.press('Escape');await nav(page,'Automation').click();await overflow(page);await page.getByRole('button',{name:'Take the tour'}).click();await overflow(page);await page.keyboard.press('Escape');}
 await page.setViewportSize({width:390,height:844});await nav(page,'Services').click();await page.screenshot({path:'.playwright/simple-mobile.png'});
 await page.goto(base+'?demo=binaya');await page.getByRole('dialog',{name:'BasePort · manager tour'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('heading',{name:'My services',exact:true}).waitFor();
 assert.deepEqual(errors,[]);await browser.close();console.log('Frontend smoke passed: both personas, provisioning, approval, drift repair, scheduling, recovery, schema rollback, stale-state gates, golden paths, agentless contract, tour isolation and 320/390px layouts.');
})().catch(e=>{console.error(e);process.exit(1)});
