const assert=require('node:assert/strict');const {chromium}=require('@playwright/test');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.DEMO_TEST_URL||'http://127.0.0.1:3000/');
 const nav=async name=>page.locator('.sidebar').getByRole('button',{name:new RegExp('^'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).click();
 await nav('Database inventory');assert.equal(await page.locator('.inventory-panel tbody tr').count(),6);
 await page.getByLabel('Inventory environment').selectOption('Development');assert.equal(await page.locator('.inventory-panel tbody tr').count(),1);
 await page.getByLabel('Inventory environment').selectOption('all');
 await page.getByRole('button',{name:'customer-insights-prod',exact:true}).click();
 await page.locator('.detail-action-row').getByRole('button',{name:'Backup',exact:true}).click();let modal=page.getByRole('dialog');
 await modal.getByRole('button',{name:'Run simulation'}).click();await page.getByRole('alert').waitFor();
 assert((await page.getByRole('alert').textContent()).includes('Production operations require'));
 await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2091');await modal.getByRole('button',{name:'Run simulation'}).click();await page.getByRole('status').waitFor();
 await nav('Backup & recovery');assert.equal(await page.locator('.backup-panel tbody tr').count(),7);
 await page.locator('.backup-panel tbody tr').first().getByRole('button',{name:'Restore clone'}).click();modal=page.getByRole('dialog');
 await modal.getByLabel('New development clone name').fill('cx-recovery-rehearsal');await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2092');
 await modal.getByRole('button',{name:'Run simulation'}).click();await modal.waitFor({state:'hidden'});
 await nav('Database inventory');assert.equal(await page.locator('.inventory-panel tbody tr').count(),7);await page.getByRole('button',{name:'cx-recovery-rehearsal',exact:true}).waitFor();
 await nav('Lifecycle operations');
 await page.locator('.lifecycle-plan').getByLabel('Database selection').selectOption('DB-1021');
 await page.getByRole('button',{name:'Run mock preflight',exact:true}).click();await page.getByRole('alert').waitFor();
 assert((await page.getByRole('alert').textContent()).includes('verified backup'));
 await page.locator('.lifecycle-plan').getByLabel('Database selection').selectOption('DB-1024');
 await page.getByRole('button',{name:'Run mock preflight',exact:true}).click();
 await page.getByRole('button',{name:'Review patch'}).click();modal=page.getByRole('dialog');
 await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2093');await modal.getByRole('button',{name:'Schedule mock operation'}).click();await modal.waitFor({state:'hidden'});
 await page.locator('.scheduled-panel tbody tr').filter({hasText:'customer-insights-prod'}).getByRole('button',{name:'Simulate execution'}).click();
 await nav('Database inventory');await page.getByRole('button',{name:'customer-insights-prod',exact:true}).click();assert((await page.locator('.db-detail-head').textContent()).includes('16.6'));
 await page.locator('.detail-action-row').getByRole('button',{name:'Upgrade',exact:true}).click();modal=page.getByRole('dialog');
 await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2094');await modal.getByLabel('Reason for change').fill('Validate major-version upgrade flow');await modal.getByLabel('Maintenance window').selectOption('Run now');
 await modal.getByRole('button',{name:'Run mock preflight'}).click();await modal.getByRole('button',{name:'Run simulation'}).click();await modal.waitFor({state:'hidden'});assert((await page.locator('.db-detail-head').textContent()).includes('17.2'));
 await page.locator('.detail-action-row').getByRole('button',{name:'Restart',exact:true}).click();modal=page.getByRole('dialog');await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2095');await modal.getByLabel('Reason for change').fill('Exercise restart');await modal.getByLabel('Maintenance window').selectOption('Run now');await modal.getByRole('button',{name:'Run simulation'}).click();await modal.waitFor({state:'hidden'});
 await nav('Migrations');await page.getByRole('button',{name:'Run migration preflight'}).click();await page.getByRole('button',{name:'Simulate migration',exact:true}).click();await page.getByRole('alert').waitFor();
 await page.locator('.migration-workbench').getByLabel('Change reference').fill('CHG-2096');await page.getByRole('button',{name:'Simulate migration',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.migration-list tbody')?.textContent.includes('Mock reconciliation passed'));
 await nav('Liquibase changes');assert.equal(await page.getByRole('button',{name:'Simulate update'}).isEnabled(),false);
 await page.getByRole('button',{name:'Validate changelog'}).click();assert.equal(await page.getByRole('button',{name:'Simulate update'}).isEnabled(),false);
 await page.getByLabel('Simulated production approval').check();await page.getByRole('button',{name:'Simulate update'}).click();await page.waitForFunction(()=>document.querySelector('.change-summary')?.textContent.includes('0 pending'));
 await page.locator('.liquibase-top').getByLabel('Database selection').selectOption('DB-1023');assert((await page.locator('.change-summary').textContent()).includes('2 pending'),'Changes leaked across targets');
 await page.locator('.liquibase-top').getByLabel('Database selection').selectOption('DB-1024');assert((await page.locator('.change-summary').textContent()).includes('0 pending'));
 await page.getByLabel('Simulated production approval').check();await page.getByRole('button',{name:'Simulate defined rollback'}).click();await page.waitForFunction(()=>document.querySelector('.change-summary')?.textContent.includes('2 pending'));
 await page.locator('.liquibase-top').getByLabel('Database selection').selectOption('DB-1022');await page.getByRole('heading',{name:'Liquibase workflow is demonstrated for relational platforms.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Simulate update'}).count(),0);
 await nav('Database inventory');await page.getByRole('button',{name:'product-catalog-dev',exact:true}).click();await page.locator('.detail-action-row').getByRole('button',{name:'Retire',exact:true}).click();modal=page.getByRole('dialog');await modal.getByLabel('Reason for change').fill('Retire the mock development service');await modal.getByRole('button',{name:'Run mock preflight'}).click();await modal.getByRole('button',{name:'Run simulation'}).click();await modal.waitFor({state:'hidden'});assert((await page.locator('.db-detail-head').textContent()).includes('Retired'));
 await page.getByRole('button',{name:'giportal',exact:true}).click();modal=page.getByRole('dialog');await modal.locator('summary').click();await modal.getByLabel('Service name',{exact:true}).fill('giportal-handoff-demo');await modal.getByRole('button',{name:'Simulate handoff'}).click();await page.getByRole('button',{name:'giportal-handoff-demo',exact:true}).waitFor();
 await nav('Audit & activity');assert(await page.locator('.audit-panel tbody tr').count()>=12);await page.locator('.audit-panel tbody tr').first().click();await page.getByRole('dialog').getByText('giportal handoff',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);console.log('DBaaS smoke passed: inventory, production controls, backup, restore clone, preflight failure, patch scheduling/execution, upgrade, restart, migration validation, scoped Liquibase update/rollback, capability boundary, retirement, giportal handoff, audit.');
 await page.close();
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
