const assert=require('node:assert/strict');
const fs=require('node:fs');
const {chromium}=require('@playwright/test');
const baseURL=process.env.DEMO_TEST_URL||'http://127.0.0.1:3000/';
const options={headless:true,args:['--no-sandbox']};if(fs.existsSync('/usr/bin/chromium'))options.executablePath='/usr/bin/chromium';
(async()=>{const browser=await chromium.launch(options);try{
 for(const mobile of [false,true]){
  const page=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(baseURL+'?view=dbre&demo=binaya');const tour=page.locator('.tour-panel');
  await tour.getByRole('heading',{name:'Binaya, meet the BasePort control plane.'}).waitFor();
  await page.keyboard.press('Tab');assert(await page.evaluate(()=>!!document.activeElement.closest('.tour-panel')));
  await tour.getByRole('button',{name:'See the golden paths'}).click();
  assert((await tour.textContent()).includes('Each run pins its revision'));
  await tour.getByRole('button',{name:'Choose a platform'}).click();
  await tour.getByRole('button',{name:mobile?'MongoDB':'SQL Server',exact:true}).click();
  assert.equal(await page.locator('.inventory-panel tbody tr').count(),1);
  await tour.getByRole('button',{name:'Review drift'}).click();
  await tour.getByRole('button',{name:'See agentless reporting'}).click();
  assert.equal(await page.locator('.report-builder').count(),1);
  await tour.getByRole('button',{name:'Accept demo evidence'}).click();
  assert.equal(await page.locator('.lifecycle-plan').count(),1);
  await tour.getByRole('button',{name:'See the developer view'}).click();
  assert.equal(await page.locator('.provisioning-workbench').count(),1);
  await tour.getByRole('button',{name:'Review the run history'}).click();
  assert.equal(await page.locator('.audit-panel tbody tr').count(),7);
  await tour.getByRole('button',{name:'Back',exact:true}).click();
  await tour.getByRole('button',{name:'Review the run history'}).click();
  assert.equal(await page.locator('.audit-panel tbody tr').count(),7,'Demo duplicated history on back/next');
  await tour.getByRole('button',{name:'See the takeaway'}).click();
  await page.waitForTimeout(250);await page.screenshot({path:`/tmp/baseport-dbaas-tour-${mobile?'mobile':'desktop'}.png`});
  await tour.getByRole('button',{name:'Replay the demo'}).click();
  await tour.getByRole('heading',{name:'Binaya, meet the BasePort control plane.'}).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.tour-panel').count(),0);
  assert(!new URL(page.url()).searchParams.has('demo'));
  const nav=async name=>{if(mobile)await page.getByLabel('Open navigation').click();await page.locator('.sidebar').getByRole('button',{name,exact:true}).click()};
  await nav('Audit & activity');assert.equal(await page.locator('.audit-panel tbody tr').count(),3);
  await nav('Database inventory');assert.equal(await page.locator('.inventory-panel tbody tr').count(),6);
  await nav('Backup & recovery');assert.equal(await page.locator('.backup-panel tbody tr').count(),6);
  await page.getByRole('button',{name:'Take an on-demand backup'}).click();
  const modal=page.getByRole('dialog');await modal.getByLabel('Change reference',{exact:false}).fill('CHG-2090');await modal.getByLabel('Simulated change approval').check();
  await modal.getByRole('button',{name:'Run simulation'}).click();await page.getByRole('status').waitFor();
  assert.equal(await page.locator('.backup-panel tbody tr').count(),7);
  if(mobile)await page.getByLabel('Open navigation').click();
  await page.locator('.sidebar').getByRole('button',{name:'Guided manager demo',exact:true}).click();
  await tour.getByRole('button',{name:'See the golden paths'}).click();await page.keyboard.press('Escape');
  assert.equal(await page.locator('.backup-panel tbody tr').count(),7,'Existing backup was lost after tour');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);await page.close();
  console.log(`${mobile?'Mobile':'Desktop'} manager demo passed: two views, golden paths, drift, agentless facts, approval context and platform choice, back/replay/exit, focus trap, and existing-backup preservation.`);
 }
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
