import React,{useState} from 'react';
import {Database,Layers3,Cloud,Leaf,ShieldCheck,ArrowRight,ArrowUpRight,Plus,Search,Clock3,HardDrive,ClipboardList,GitBranch,RefreshCw,Check} from 'lucide-react';
import {platforms,platformById,backupProvider} from './data.js';
import {serviceState} from './serviceStore.js';
import {Badge,Empty} from './ui.jsx';
function PlatformMark({platform,small=false}) {return <span className={`platform-mark ${small?'small':''}`} style={{background:platform.bg,color:platform.color}}>{platform.glyph==='postgres'?<svg viewBox="0 0 36 36" fill="none"><path d="M10 24C5 21 5 9 12 7c4-2 9-2 13 1 5 4 4 12 1 16l-4 2-1 5-4 1-1-10-5 3-4-1" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round"/><path d="M15 12c3-3 9-2 10 2l-1 10M16 12l-1 8 3 2 4-1M10 15l2 2M21 14h1M13 24l-3 5H6" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg>:platform.glyph==='oracle'?<span className="oracle-mark"/>:platform.glyph==='mongo'?<Leaf size={small?19:31} strokeWidth={1.6} fill="currentColor"/>:platform.glyph==='db2'?<span className="db2-mark">Db2</span>:platform.glyph==='cloudera'?<span className="cloudera-mark">C.</span>:<svg viewBox="0 0 36 36" fill="none"><path d="m10 4 17 8-18 8 19 8-17 5 4-11 12-10-8-4-9-4Z" stroke="currentColor" strokeWidth="1.4"/><path d="m10 4 5 18 13 6M9 20l18-8M11 33l6-18 10-3M12 12l13 11" stroke="currentColor" strokeWidth="1"/></svg>}</span>}
function HeroArt(){return <div className="hero-art" aria-hidden="true"><div className="orbital orbit-one"/><div className="orbital orbit-two"/><div className="art-grid"/><div className="floating-chip chip-a"><Database size={19}/></div><div className="floating-chip chip-b"><Cloud size={22}/></div><div className="floating-chip chip-c"><ShieldCheck size={21}/></div><div className="server-stack"><div className="server-top"><Layers3 size={41} strokeWidth={1.2}/></div>{[0,1,2].map(i=><div className="server-layer" key={i}><span/><span/><i/><i/></div>)}<div className="server-shadow"/></div><span className="art-dot dot-a"/><span className="art-dot dot-b"/><span className="art-plus">+</span></div>}
function Metric({label,value,foot,icon:Icon}){return <article className="original-stat"><div><span>{label}</span><Icon size={18}/></div><strong>{value}</strong><small>{foot}</small></article>}
export function Catalog({space,onNew}){
 const options=space.platform?platforms.filter(p=>p.id===space.platform):platforms;
 return <section className="original-catalog"><div className="original-section-heading"><div><h2>Find your foundation</h2><p>Enterprise platforms. Governed service paths.</p></div></div><div className="original-platform-grid">{options.map(p=><button key={p.id} className="original-platform-card" onClick={()=>onNew(p.id)} aria-label={`Request ${p.name}`}><div><PlatformMark platform={p}/><small>{p.relational?'Relational':p.id==='mongodb'?'Document':'Data platform'}</small></div><h3>{p.name}</h3><p>{p.relational?'Managed database service':p.id==='mongodb'?'Managed document service':'Managed data platform'}</p><span>Configure service <ArrowRight size={13}/></span></button>)}</div></section>
}
export function Inventory({store,onSelect,compact=false,globalSearch='',attentionOnly=false}){
 const [query,setQuery]=useState(''),[platform,setPlatform]=useState('all'),[environment,setEnvironment]=useState('all');
 const rows=store.services.filter(s=>s.status!=='Retired'&&(!attentionOnly||serviceState(s,store.evidence).label!=='Ready')&&(platform==='all'||s.platform===platform)&&(environment==='all'||s.environment===environment)&&`${s.name} ${s.team} ${platformById(s.platform).name}`.toLowerCase().includes((globalSearch||query).toLowerCase()));
 return <section className="panel original-inventory">{!compact&&<div className="list-toolbar"><label className="search-field"><Search size={16}/><input aria-label="Search databases" placeholder="Find a database in this space" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="list-filters"><select aria-label="Platform filter" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">All platforms in space</option>{platforms.filter(p=>store.services.some(s=>s.platform===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Environment filter" value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="all">All environments</option>{['Production','Staging','Development'].map(e=><option key={e}>{e}</option>)}</select></div></div>}<div className="data-scroll"><table><thead><tr><th>DATABASE / PLATFORM</th><th>ENVIRONMENT</th>{!compact&&<th>OWNER</th>}<th>PROTECTION</th><th>SERVICE STATE</th><th/></tr></thead><tbody>{rows.slice(0,compact?4:rows.length).map(s=><tr key={s.id}><td><div className="original-database-cell"><PlatformMark platform={platformById(s.platform)} small/><span><button className="service-name" onClick={()=>onSelect(s.id)}>{s.name}</button><small>{platformById(s.platform).name} · {s.version}</small></span></div></td><td><span className="environment">{s.environment}</span></td>{!compact&&<td>{s.team}</td>}<td><Badge label={s.backup} tone={s.backup==='Protected'?'good':'attention'}/></td><td><Badge {...serviceState(s,store.evidence)}/></td><td><button className="icon-button" aria-label={`Manage ${s.name}`} onClick={()=>onSelect(s.id)}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>{!rows.length&&<Empty>No databases match this space and its filters.</Empty>}</section>
}
export function Overview({store,space,persona,onNavigate,onNew,onService,onRequest}){
 const active=store.services.filter(s=>s.status!=='Retired'),pending=store.requests.filter(r=>r.status!=='Completed'),protectedCount=active.filter(s=>s.backup==='Protected').length;
 return <><section className="welcome-banner"><div className="welcome-content"><span className="banner-tag">{space.kind.toUpperCase()} SPACE · DBAAS</span><h2>{persona==='Developer'?<>Your databases.<br/>Your space.</>:<>Your platform.<br/>Under control.</>}</h2><p>{persona==='Developer'?'Build and manage the services assigned to you.':'One operating view for your assigned platform.'}</p><button className="button dark" onClick={()=>onNavigate(persona==='Developer'?'Service catalog':'Lifecycle operations')}>{persona==='Developer'?'Explore the catalog':'Manage lifecycle'}<ArrowRight size={16}/></button></div><HeroArt/></section><div className="original-stats-grid"><Metric label="Active services" value={active.length} foot="In this space" icon={Database}/><Metric label="Pending requests" value={pending.length} foot="Approval and execution" icon={ClipboardList}/><Metric label="Protected services" value={`${protectedCount} / ${active.length}`} foot="Configured recovery policy" icon={ShieldCheck}/><Metric label="Storage allocated" value={`${active.reduce((sum,s)=>sum+s.storage,0)} GB`} foot="Declared service capacity" icon={HardDrive}/></div><Catalog space={space} onNew={onNew}/><div className="original-overview-bottom"><section><div className="original-section-heading"><h2>Space databases</h2><button className="text-button" onClick={()=>onNavigate('Databases')}>View all <ArrowRight size={14}/></button></div><Inventory store={store} compact onSelect={onService}/></section><section className="panel original-activity"><div className="card-heading"><h2>Recent activity</h2><span className="small-label">This space</span></div>{store.requests.slice(0,4).map(r=><button key={r.id} className="original-activity-row" onClick={()=>onRequest(r.id)}><span><GitBranch size={16}/></span><div><strong>{r.action==='Provision'?'Service requested':r.action}</strong><small>{r.serviceName}</small><Badge label={r.status}/></div><ArrowRight size={14}/></button>)}{!store.requests.length&&<Empty>No activity in this space yet.</Empty>}</section></div></>;
}
export function Recovery({store,onAction}){return <section className="panel original-recovery"><div className="card-heading"><h2>Backup & recovery</h2><span className="small-label">This space</span></div><div className="data-scroll"><table><thead><tr><th>DATABASE</th><th>PROVIDER</th><th>RESTORE POINT</th><th>STATUS</th><th/></tr></thead><tbody>{store.backups.map(b=>{const s=store.services.find(s=>s.id===b.serviceId);return <tr key={b.id}><td><strong>{s.name}</strong><small>{platformById(s.platform).name}</small></td><td>{backupProvider(s)}</td><td>{b.created}<small>{b.retention}</small></td><td><Badge label={b.status} tone={b.status==='Verified'?'good':'attention'}/></td><td><button className="text-button" disabled={b.status!=='Verified'||s.status==='Retired'} onClick={()=>onAction(s.id,'Restore clone',b.id)}>Restore clone <ArrowRight size={13}/></button></td></tr>})}</tbody></table></div>{!store.backups.length&&<Empty>No restore points in this space.</Empty>}<div className="original-backup-actions">{store.services.filter(s=>s.status!=='Retired').map(s=><button className="button secondary" key={s.id} onClick={()=>onAction(s.id,'Backup')}>Backup {s.name}</button>)}</div></section>}
export function ActionWorkbench({store,onAction,mode='Lifecycle operations'}){
 const active=store.services.filter(s=>s.status!=='Retired'),eligible=active.filter(s=>mode!=='Schema delivery'||platformById(s.platform).relational),[id,setId]=useState(eligible[0]?.id||''),[action,setAction]=useState(mode==='Migrations'?'Migrate':mode==='Schema delivery'?'Schema update':'Patch');
 const options=mode==='Migrations'?['Migrate']:mode==='Schema delivery'?['Schema update','Schema rollback']:['Restart','Patch','Upgrade','Apply baseline','Retire'];
 if(!eligible.length)return <section className="panel"><Empty>{mode==='Schema delivery'?'This platform uses native change tooling.':'No active databases in this space.'}</Empty></section>;
 return <section className="panel original-workbench"><div><span className="label">GOVERNED SERVICE WORKFLOW</span><h2>{mode}</h2><p>Select a database in this space. BasePort prepares the change and routes approval.</p><label>Database<select value={id} onChange={e=>setId(e.target.value)}>{eligible.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}>{options.map(a=><option key={a}>{a}</option>)}</select></label><button className="button primary" disabled={!eligible.some(s=>s.id===id)} onClick={()=>onAction(id,action)}>Review request <ArrowRight size={15}/></button></div><div className="original-workflow-preview"><ShieldCheck size={30}/><h3>One consistent path</h3>{['Service context','Change prepared','Reviewer approval','Existing execution layer','Result and history'].map((s,i)=><span key={s}><i>{i+1}</i>{s}</span>)}</div></section>
}
function Rollups({rows,kind}){return <section className="panel fleet-rollups"><div className="card-heading"><h2>{kind==='platform'?'Platform portfolio':'Business portfolio'}</h2><span className="small-label">Aggregate view</span></div><div className="data-scroll"><table><thead><tr><th>{kind==='platform'?'PLATFORM':'BUSINESS UNIT'}</th><th>SERVICES</th><th>PRODUCTION</th><th>PROTECTED</th><th>NEEDS ATTENTION</th><th>CAPACITY</th></tr></thead><tbody>{rows.map(r=><tr key={r.id||r.name}><td><strong>{r.name}</strong></td><td>{r.count}</td><td>{r.production}</td><td>{r.protected} / {r.count}</td><td>{r.attention}</td><td>{r.storage} GB</td></tr>)}</tbody></table></div></section>}
export function ManagementView({summary,page}){
 const total=summary.total;
 return <div className="management-view">{page==='Overview'&&<section className="welcome-banner"><div className="welcome-content"><span className="banner-tag">FLEET VISIBILITY · READ-ONLY</span><h2>One fleet.<br/>A clear picture.</h2><p>Service coverage, business ownership and lifecycle demand.</p><span className="management-readonly"><ShieldCheck size={14}/>Portfolio summaries</span></div><HeroArt/></section>}<div className="original-stats-grid"><Metric label="Fleet services" value={total.count} foot={`${total.production} in production`} icon={Database}/><Metric label="Protected services" value={`${total.protected} / ${total.count}`} foot="Recovery-policy coverage" icon={ShieldCheck}/><Metric label="Service attention" value={total.attention} foot="Policy or freshness gaps" icon={Clock3}/><Metric label="Open requests" value={summary.requests} foot="Lifecycle demand" icon={ClipboardList}/></div>{page!=='Business portfolio'&&<Rollups rows={summary.platforms} kind="platform"/>}{page!=='Fleet insights'&&<Rollups rows={summary.teams} kind="business"/>}<section className="panel fleet-environments"><h2>Environment distribution</h2><div>{summary.environments.map(e=><div key={e.name}><span>{e.name}</span><span className="fleet-bar"><i style={{width:`${total.count?100*e.count/total.count:0}%`}}/></span><strong>{e.count}</strong></div>)}</div><p>Capacity is declared allocation. Attention combines policy findings and missing or stale service facts.</p></section></div>
}
