import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,CheckCircle2,Link2,Network,ShieldCheck,Database,RefreshCw,Server,Code2,Activity,Clock3} from 'lucide-react';
import {backupProvider,nativeConsole,platformById} from './data';
const tools=[
 {name:'giportal + Ansible',layer:'PROVISIONING',description:'Provision through giportal and approved AAP automation.',context:'Service specification, owner, environment, giportal request ID and Ansible job ID',owner:'Infrastructure provisioning team',icon:Server},
 {name:'ServiceNow',layer:'GOVERNANCE',description:'Generate change records and route approvals.',context:'Service identity, CI reference, change reference and approval state',owner:'Enterprise change management',icon:ShieldCheck},
 {name:'Rubrik / native recovery',layer:'PROTECTION',description:'Use the configured backup and recovery provider.',context:'Provider binding, recovery policy, restore-point ID and job outcome',owner:'Backup and recovery teams',icon:Database},
 {name:'Vendor native consoles',layer:'ENGINE OPERATIONS',description:'Open the native console with service context.',context:'Database identity, environment and native resource reference',owner:'Platform DBAs',icon:Network},
 {name:'Git + Liquibase',layer:'CHANGE DELIVERY',description:'Connect reviewed schema releases to the service.',context:'Repository, changelog, target, pipeline run and approved change',owner:'Application teams and DBAs',icon:Code2},
 {name:'Grafana + Elastic',layer:'OBSERVABILITY',description:'Open existing dashboards and logs for investigation.',context:'Service identity, environment and dashboard / log scope',owner:'Observability and operations teams',icon:Activity},
];
export function ConnectedStack({onOpen,compact=false}){return <section className={`connected-stack ${compact?'compact-stack':''}`}>
 {!compact&&<div className="stack-intro"><span className="eyebrow">THE REASON FOR BASEPORT</span><h2>Keep the tools. Connect the service.</h2><p>One service record across your existing stack.</p><div className="stack-context"><Link2 size={22}/><div><strong>BasePort owns the service experience</strong><span>Identity · policy · workflow · evidence</span></div></div></div>}
 <div className="tool-grid">{tools.map(({icon:Icon,...tool})=><article className="tool-card" key={tool.name}><div className="tool-card-top"><Icon size={22}/><span>{tool.layer}</span></div><h3>{tool.name}</h3><p>{tool.description}</p><div className="tool-owner">{tool.owner}</div><button className="text-button" onClick={()=>onOpen(tool.name)}>Open handoff preview <ArrowUpRight size={14}/></button></article>)}</div>
 {!compact&&<details className="plain-details"><summary>Integration contracts</summary><p>Shared identity, scoped access, validated approval state and reliable job callbacks are required in production. All connections are mocks.</p></details>}
 </section>}
export function ToolHandoff({tool,service}){const native=tool===nativeConsole(service||{platform:'postgres'});const entry=tools.find(t=>t.name===tool)||(native?tools[3]:tools[3]);return <div className="tool-handoff"><span className="eyebrow">CONTEXTUAL HANDOFF · PROTOTYPE</span><h2>{tool}</h2><p className="modal-description">{entry.description}</p><div className="handoff-context"><div><span>Service</span><strong>{service?.name||'Selected DBaaS service'}</strong></div><div><span>Environment</span><strong>{service?.environment||'Passed from service context'}</strong></div><div><span>Context passed</span><strong>{entry.context}</strong></div><div><span>Responsible team</span><strong>{entry.owner}</strong></div></div><div className="integration-boundary"><Link2 size={20}/><p>No external connection. This previews the service context passed to the tool.</p></div></div>}
export function ExecutionRoute({service,action,ticket,onOpen}){
 if(!service)return null;
 const recovery=/Backup|Restore/i.test(action), schema=/Liquibase/i.test(action);
 const execution=/Provision/i.test(action)?'giportal → Ansible':recovery?`${backupProvider(service)} recovery`:schema?'Git + Liquibase':/Patch|Upgrade|Restart|Retire|remediation/i.test(action)?'AAP / native adapters':nativeConsole(service);
 return <div className="execution-route"><div className="execution-route-label">SERVICE CONTEXT & EXECUTION ROUTE</div><div className="route-nodes"><span>BasePort service record</span><ArrowRight size={13}/><span>ServiceNow{ticket?` · ${ticket}`:' · approval context'}</span><ArrowRight size={13}/><span>{execution}</span><ArrowRight size={13}/><span>Correlated outcome</span></div><p>{recovery?'Provider binding determines the backup or recovery adapter.':schema?'Reviewed changes run through a configured delivery pipeline.':'Native tooling and approved automation retain engine-specific execution.'} Approval checks and tool calls are simulated.</p>{onOpen&&<div className="context-links">{[nativeConsole(service),backupProvider(service)==='Rubrik'?'Rubrik / native recovery':'Vendor native consoles','Grafana + Elastic','ServiceNow'].filter((v,i,a)=>a.indexOf(v)===i).map(tool=><button className="text-button" key={tool} onClick={()=>onOpen(tool)}>{tool}<ArrowUpRight size={13}/></button>)}</div>}</div>
}
export function ServiceInsights({services,backups,operations,onNavigate}){
 const active=services.filter(s=>s.status!=='Retired');
 const coverage=active.filter(s=>s.team).length, protectedCount=active.filter(s=>s.backup==='Protected').length;
 return <section className="insights-panel"><div className="insight-intro"><h2>Service delivery</h2><p>Estate readiness · demo data</p></div><div className="insight-cards">{[['Ownership coverage',`${coverage}/${active.length}`,'Active services with a named owning team'],['Protection readiness',`${protectedCount}/${active.length}`,'Services meeting the illustrative recovery policy'],['Work completed',operations.filter(o=>o.status==='Completed').length,'Recorded completions in the demo activity trail'],['Storage entitlement',`${active.reduce((n,s)=>n+s.storage,0)} GB`,'Declared allocation across active services']].map(([label,value,detail])=><article key={label}><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>)}</div><div className="insight-grid"><section className="panel estate-coverage"><h3>Service coverage by platform</h3>{['oracle','sqlserver','db2','postgres','mongodb','cloudera'].map(id=><div key={id}><span>{platformById(id).name}</span><div className="coverage-track"><i style={{width:`${active.filter(s=>s.platform===id).length/Math.max(1,active.length)*100}%`}}/></div><strong>{active.filter(s=>s.platform===id).length}</strong></div>)}</section><section className="panel insight-actions"><h3>Turn insight into service work</h3><button onClick={()=>onNavigate('Backup & recovery')}><ShieldCheck size={20}/><span><strong>{active.length-protectedCount} protection gaps</strong><small>Review provider policies and restore readiness</small></span><ArrowRight size={16}/></button><button onClick={()=>onNavigate('Lifecycle operations')}><RefreshCw size={20}/><span><strong>{active.filter(s=>s.patch==='Patch available').length} services with patch work</strong><small>Coordinate owners, approval and maintenance windows</small></span><ArrowRight size={16}/></button><button onClick={()=>onNavigate('Audit & activity')}><Clock3 size={20}/><span><strong>{operations.filter(o=>['Scheduled','In review'].includes(o.status)).length} actions awaiting completion</strong><small>Review the service delivery queue</small></span><ArrowRight size={16}/></button></section></div><div className="integration-boundary"><Activity size={22}/><p>Performance, logs & alerts: native consoles, Grafana and Elastic.</p><button className="text-button" onClick={()=>onNavigate('Connected tools')}>Explore tool handoffs <ArrowRight size={14}/></button></div></section>
}
const stages=['BasePort request','Change & approval','giportal workflow','Ansible automation','Inventory registration'];
export function Provisioning({platforms,services,onComplete,onInventory,initialPlatform='postgres'}){
 const [form,setForm]=useState({name:'',platform:initialPlatform,environment:'Development',team:'Policy Servicing',size:'64',change:''});
 const [stage,setStage]=useState(-1),[error,setError]=useState(''),[record,setRecord]=useState(null);const timer=useRef(null);
 const running=stage>=0&&stage<stages.length;
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 const update=(key,value)=>{setForm({...form,[key]:value});setError('')};
 const run=()=>{
  if(!/^[a-z][a-z0-9-]{2,47}$/.test(form.name)||services.some(s=>s.name===form.name)){setError('Use a unique name with 3–48 lowercase letters, numbers or hyphens.');return}
  if(!form.team.trim()){setError('Specify an owning team.');return}

  setError('');const id=Date.now();setRecord({request:`BP-${id}`,workflow:`GIP-DEMO-${id}`,job:`ANS-DEMO-${id}`,change:`CHG-${String(id).slice(-6)}`});setStage(0);
  timer.current=setTimeout(()=>setStage(1),450);
 };
 const approve=()=>{
  const advance=next=>{timer.current=setTimeout(()=>{setStage(next);if(next<stages.length)advance(next+1);else{const p=platformById(form.platform);onComplete({...form,change:record.change,id:`DB-${record.request.slice(3)}`,version:p.patch,status:'Active',storage:Number(form.size),backup:'Unprotected',patch:'Up to date',origin:record.workflow,requestId:record.request,jobId:record.job,schema:p.relational?'v0':'Platform-managed'})}},450)};
  setStage(2);advance(3);
 };

 return <section className="panel provisioning-workbench"><div className="provision-intro"><span className="eyebrow">GOLDEN PATH · DATABASE SERVICE</span><h2>Request a database service</h2><p>Approved specification. Automatic change record. Existing automation.</p></div><div className="provision-grid"><div className="provision-form" inert={running||stage===stages.length?true:undefined}><label>Service name<input value={form.name} placeholder="policy-analytics-dev" onChange={e=>update('name',e.target.value)}/></label><div className="form-two-col"><label>Platform<select value={form.platform} onChange={e=>update('platform',e.target.value)}>{platforms.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Environment<select value={form.environment} onChange={e=>update('environment',e.target.value)}>{['Development','Staging','Production'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Owning team<input value={form.team} onChange={e=>update('team',e.target.value)}/></label><div className="form-two-col"><label>Storage entitlement<select value={form.size} onChange={e=>update('size',e.target.value)}>{[32,64,128,256].map(v=><option value={v} key={v}>{v} GB</option>)}</select></label><div className="auto-change-note"><ShieldCheck size={17}/><span>Change record generated<br/>Approval routed automatically</span></div></div></div><div className="provision-trace"><span className="eyebrow">MOCK EXECUTION PLAN</span>{stages.map((name,i)=><div className={`provision-stage ${stage>i?'done':stage===i?'running':''}`} key={name}><span>{stage>i?<CheckCircle2 size={17}/>:stage===i?<RefreshCw size={17} className="spin"/>:i+1}</span><div><strong>{name}</strong><small>{['Capture service specification','Generate change; wait for reviewer','Invoke provisioning workflow','Run approved playbooks','Register service & policy gap'][i]}</small></div></div>)}{record&&<div className="request-correlations"><span>Change: {record.change}</span><span>Request: {record.request}</span><span>Workflow: {record.workflow}</span><span>Job: {record.job}</span></div>}</div></div>{error&&<p className="db-error" role="alert">{error}</p>}<div className="provision-footer"><p>{stage===stages.length?'Registered · protection policy required.':'Demo · approvals and automation are simulated.'}</p>{stage===1?<button className="button primary" onClick={approve}>Simulate reviewer approval <ShieldCheck size={15}/></button>:stage===stages.length?<button className="button primary" onClick={onInventory}>View registered service <ArrowRight size={15}/></button>:<button className="button primary" disabled={running} onClick={run}>{running?'Simulating provisioning…':'Simulate service request'}<ArrowRight size={15}/></button>}</div></section>
}
