import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,CheckCircle2,Link2,Network,ShieldCheck,Database,RefreshCw,Server,Code2,Activity,Clock3} from 'lucide-react';
import {backupProvider,nativeConsole,platformById} from './data';
const tools=[
 {name:'giportal + Ansible',layer:'PROVISIONING',description:'BasePort submits the service request to the existing giportal flow. Ansible provisions VMs and executes approved infrastructure and engine automation.',context:'Service specification, owner, environment, giportal request ID and Ansible job ID',owner:'Infrastructure provisioning team',icon:Server},
 {name:'ServiceNow',layer:'GOVERNANCE',description:'Keep change approvals, maintenance windows, incidents and CMDB relationships in the enterprise system of record.',context:'Service identity, CI reference, change reference and approval state',owner:'Enterprise change management',icon:ShieldCheck},
 {name:'Rubrik / native recovery',layer:'PROTECTION',description:'Expose supported recovery policies, restore points and restore requests from the service’s configured provider. Rubrik coverage varies by service.',context:'Provider binding, recovery policy, restore-point ID and job outcome',owner:'Backup and recovery teams',icon:Database},
 {name:'Vendor native consoles',layer:'ENGINE OPERATIONS',description:'Keep detailed engine administration and diagnostics in Oracle Enterprise Manager, SSMS, Db2 consoles, pgAdmin, MongoDB Ops Manager and Cloudera Manager.',context:'Database identity, environment and native resource reference',owner:'Platform DBAs',icon:Network},
 {name:'Git + Liquibase',layer:'CHANGE DELIVERY',description:'Connect repository releases and reviewed schema changes to the target service, change approval, deployment runner and rollback metadata.',context:'Repository, changelog, target, pipeline run and approved change',owner:'Application teams and DBAs',icon:Code2},
 {name:'Grafana + Elastic',layer:'OBSERVABILITY',description:'Use the established dashboards, logs and alerts for investigation. BasePort provides service context and high-level delivery insights.',context:'Service identity, environment and dashboard / log scope',owner:'Observability and operations teams',icon:Activity},
];
export function ConnectedStack({onOpen,compact=false}){return <section className={`connected-stack ${compact?'compact-stack':''}`}>
 {!compact&&<div className="stack-intro"><span className="eyebrow">THE REASON FOR BASEPORT</span><h2>Keep the tools. Connect the service.</h2><p>A single database spans requests, infrastructure, recovery, schema delivery and operations. BasePort gives teams a consistent service record and workflow across those boundaries.</p><div className="stack-context"><Link2 size={22}/><div><strong>BasePort owns the service experience</strong><span>Identity & ownership · policy & readiness · workflow routing · correlated execution history</span></div></div></div>}
 <div className="tool-grid">{tools.map(({icon:Icon,...tool})=><article className="tool-card" key={tool.name}><div className="tool-card-top"><Icon size={22}/><span>{tool.layer}</span></div><h3>{tool.name}</h3><p>{tool.description}</p><div className="tool-owner">{tool.owner}</div><button className="text-button" onClick={()=>onOpen(tool.name)}>Preview contextual handoff <ArrowUpRight size={14}/></button></article>)}</div>
 {!compact&&<div className="integration-boundary"><ShieldCheck size={21}/><p><strong>Proposed integration contracts, illustrated with mock data.</strong> Production connections would require shared identity, scoped access, provider adapters, validated approval state and reliable job callbacks. Each system retains its own source records.</p></div>}
 </section>}
export function ToolHandoff({tool,service}){const native=tool===nativeConsole(service||{platform:'postgres'});const entry=tools.find(t=>t.name===tool)||(native?tools[3]:tools[3]);return <div className="tool-handoff"><span className="eyebrow">CONTEXTUAL HANDOFF · PROTOTYPE</span><h2>{tool}</h2><p className="modal-description">{entry.description}</p><div className="handoff-context"><div><span>Service</span><strong>{service?.name||'Selected DBaaS service'}</strong></div><div><span>Environment</span><strong>{service?.environment||'Passed from service context'}</strong></div><div><span>Context passed</span><strong>{entry.context}</strong></div><div><span>Responsible team</span><strong>{entry.owner}</strong></div></div><div className="integration-boundary"><Link2 size={20}/><p>A production handoff would open an authorized tool with this service selected. No external connection or real enterprise URL is configured in this POC.</p></div></div>}
export function ExecutionRoute({service,action,ticket,onOpen}){
 if(!service)return null;
 const recovery=/Backup|Restore/i.test(action), schema=/Liquibase/i.test(action);
 const execution=/Provision/i.test(action)?'giportal → Ansible':recovery?`${backupProvider(service)} recovery`:schema?'Git + Liquibase':nativeConsole(service);
 return <div className="execution-route"><div className="execution-route-label">SERVICE CONTEXT & EXECUTION ROUTE</div><div className="route-nodes"><span>BasePort service record</span><ArrowRight size={13}/><span>ServiceNow{ticket?` · ${ticket}`:' · approval context'}</span><ArrowRight size={13}/><span>{execution}</span><ArrowRight size={13}/><span>Correlated outcome</span></div><p>{recovery?'Provider binding determines the backup or recovery adapter.':schema?'Reviewed changes run through a configured delivery pipeline.':'Native tooling and approved automation retain engine-specific execution.'} Approval checks and tool calls are simulated.</p>{onOpen&&<div className="context-links">{[nativeConsole(service),backupProvider(service)==='Rubrik'?'Rubrik / native recovery':'Vendor native consoles','Grafana + Elastic','ServiceNow'].filter((v,i,a)=>a.indexOf(v)===i).map(tool=><button className="text-button" key={tool} onClick={()=>onOpen(tool)}>{tool}<ArrowUpRight size={13}/></button>)}</div>}</div>
}
export function ServiceInsights({services,backups,operations,onNavigate}){
 const active=services.filter(s=>s.status!=='Retired');
 const coverage=active.filter(s=>s.team).length, protectedCount=active.filter(s=>s.backup==='Protected').length;
 return <section className="insights-panel"><div className="insight-intro"><h2>How well are we delivering DBaaS?</h2><p>Service coverage, lifecycle readiness and demand across the estate. Figures reflect this in-memory demo, rather than telemetry from database engines.</p></div><div className="insight-cards">{[['Ownership coverage',`${coverage}/${active.length}`,'Active services with a named owning team'],['Protection readiness',`${protectedCount}/${active.length}`,'Services meeting the illustrative recovery policy'],['Work completed',operations.filter(o=>o.status==='Completed').length,'Recorded completions in the demo activity trail'],['Storage entitlement',`${active.reduce((n,s)=>n+s.storage,0)} GB`,'Declared allocation across active services']].map(([label,value,detail])=><article key={label}><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>)}</div><div className="insight-grid"><section className="panel estate-coverage"><h3>Service coverage by platform</h3>{['oracle','sqlserver','db2','postgres','mongodb','cloudera'].map(id=><div key={id}><span>{platformById(id).name}</span><div className="coverage-track"><i style={{width:`${active.filter(s=>s.platform===id).length/Math.max(1,active.length)*100}%`}}/></div><strong>{active.filter(s=>s.platform===id).length}</strong></div>)}</section><section className="panel insight-actions"><h3>Turn insight into service work</h3><button onClick={()=>onNavigate('Backup & recovery')}><ShieldCheck size={20}/><span><strong>{active.length-protectedCount} protection gaps</strong><small>Review provider policies and restore readiness</small></span><ArrowRight size={16}/></button><button onClick={()=>onNavigate('Lifecycle operations')}><RefreshCw size={20}/><span><strong>{active.filter(s=>s.patch==='Patch available').length} services with patch work</strong><small>Coordinate owners, approval and maintenance windows</small></span><ArrowRight size={16}/></button><button onClick={()=>onNavigate('Audit & activity')}><Clock3 size={20}/><span><strong>{operations.filter(o=>['Scheduled','In review'].includes(o.status)).length} actions awaiting completion</strong><small>Review the service delivery queue</small></span><ArrowRight size={16}/></button></section></div><div className="integration-boundary"><Activity size={22}/><p>Detailed performance, alerts and logs remain in vendor consoles, Grafana and Elastic. BasePort links the service to those tools.</p><button className="text-button" onClick={()=>onNavigate('Connected tools')}>Explore tool handoffs <ArrowRight size={14}/></button></div></section>
}
const stages=['BasePort request','ServiceNow approval','giportal workflow','Ansible automation','Inventory registration'];
export function Provisioning({platforms,services,onComplete,onInventory}){
 const [form,setForm]=useState({name:'',platform:'postgres',environment:'Development',team:'Policy Servicing',size:'64',change:''});
 const [stage,setStage]=useState(-1),[error,setError]=useState(''),[record,setRecord]=useState(null);const timer=useRef(null);
 const running=stage>=0&&stage<stages.length;
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 const update=(key,value)=>{setForm({...form,[key]:value});setError('')};
 const run=()=>{
  if(!/^[a-z][a-z0-9-]{2,47}$/.test(form.name)||services.some(s=>s.name===form.name)){setError('Use a unique name with 3–48 lowercase letters, numbers or hyphens.');return}
  if(!form.team.trim()){setError('Specify an owning team.');return}
  if(form.environment==='Production'&&!/^CHG-\d{3,}$/i.test(form.change)){setError('Production requests require a change reference such as CHG-2098.');return}
  setError('');const id=Date.now();setRecord({request:`BP-${id}`,workflow:`GIP-DEMO-${id}`,job:`ANS-DEMO-${id}`});setStage(0);
  const advance=next=>{timer.current=setTimeout(()=>{setStage(next);if(next<stages.length)advance(next+1);else{const p=platformById(form.platform);onComplete({...form,id:`DB-${id}`,version:p.patch,status:'Active',storage:Number(form.size),backup:'Unprotected',patch:'Up to date',origin:`GIP-DEMO-${id}`,requestId:`BP-${id}`,jobId:`ANS-DEMO-${id}`,schema:p.relational?'v0':'Platform-managed'})}},550)};
  advance(1);
 };
 return <section className="panel provisioning-workbench"><div className="provision-intro"><span className="eyebrow">REQUEST THROUGH BASEPORT · EXECUTE THROUGH EXISTING AUTOMATION</span><h2>Request a database service</h2><p>The service request stays connected to its owner, change reference, provisioning workflow and execution job.</p></div><div className="provision-grid"><div className="provision-form" inert={running||stage===stages.length?true:undefined}><label>Service name<input value={form.name} placeholder="policy-analytics-dev" onChange={e=>update('name',e.target.value)}/></label><div className="form-two-col"><label>Platform<select value={form.platform} onChange={e=>update('platform',e.target.value)}>{platforms.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Environment<select value={form.environment} onChange={e=>update('environment',e.target.value)}>{['Development','Staging','Production'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Owning team<input value={form.team} onChange={e=>update('team',e.target.value)}/></label><div className="form-two-col"><label>Storage entitlement<select value={form.size} onChange={e=>update('size',e.target.value)}>{[32,64,128,256].map(v=><option value={v} key={v}>{v} GB</option>)}</select></label><label>Change reference<input value={form.change} placeholder={form.environment==='Production'?'CHG-2098 · required':'Optional for development'} onChange={e=>update('change',e.target.value)}/></label></div></div><div className="provision-trace"><span className="eyebrow">MOCK EXECUTION PLAN</span>{stages.map((name,i)=><div className={`provision-stage ${stage>i?'done':stage===i?'running':''}`} key={name}><span>{stage>i?<CheckCircle2 size={17}/>:stage===i?<RefreshCw size={17} className="spin"/>:i+1}</span><div><strong>{name}</strong><small>{['Capture specification & service owner','Illustrative approval gate; no live approval check','Invoke the existing provisioning flow','VM and engine setup through approved playbooks','Record service identity & recovery policy gap'][i]}</small></div></div>)}{record&&<div className="request-correlations"><span>Request: {record.request}</span><span>Workflow: {record.workflow}</span><span>Job: {record.job}</span></div>}</div></div>{error&&<p className="db-error" role="alert">{error}</p>}<div className="provision-footer"><p>{stage===stages.length?'Service registered. Configure protection before production use.':'All approvals and execution steps are mocked. No VMs or databases are provisioned.'}</p>{stage===stages.length?<button className="button primary" onClick={onInventory}>View registered service <ArrowRight size={15}/></button>:<button className="button primary" disabled={running} onClick={run}>{running?'Simulating provisioning…':'Simulate service request'}<ArrowRight size={15}/></button>}</div></section>
}
